library(tidyverse)
source("code/utils.R")
source("code/parameters.R")

# ==============================================================================
# Effective overdispersion k_eff(psi, t) from punctuated infectiousness
#
# Computes the time-varying effective negative binomial dispersion parameter
# k_eff(t) for each punctuation level psi, and compares theoretical variance
# predictions with empirical simulation data.
#
# Key quantities:
#   p_bar(t)    = E[S(t + l + epsilon)]  — mean prob. a contact at gen-time tau
#                 is still susceptible, averaging over individual timing
#   Var_l(t)    = E_l[p_bar(t+l)^2] - (E_l[p_bar(t+l)])^2  — variance from
#                 synchronization of infection attempts
#   k_eff(t)    = p_bar(t)^2 / Var_l(t)
#   D(t)        = 1 + R0 * Var_l(t) / p_bar(t)  — overdispersion index
#
# Requires cached simulation output in output/cuminf_df_{pathogen}_n{popsize}_s{nsim}.csv
# (generated by episims_gamma.R).
# ==============================================================================

# ==============================================================================
# 1. Global parameters
# ==============================================================================

popsize    <- 1000
nsim       <- 1000
psivals    <- c(0, 0.25, 0.5, 0.75, 1)
psi_colors <- c("0" = "red", "0.25" = "orange", "0.5" = "blue",
                "0.75" = "purple", "1" = "black")

# ==============================================================================
# 2. Helper functions
# ==============================================================================

#' Compute Gamma convolution weights using CDF differences
#'
#' Uses pgamma to compute P(bin_k) = P(k*dt <= X < (k+1)*dt) which is
#' numerically stable even when shape < 1 (where dgamma has a singularity at 0).
#'
#' @param times  Time grid (assumed equally spaced starting at 0)
#' @param shape  Gamma shape parameter
#' @param rate   Gamma rate parameter
#' @param dt     Time step
#' @return Numeric vector of weights summing to ~1
gamma_weights <- function(times, shape, rate, dt) {
	# CDF at bin edges: P(X <= (k+0.5)*dt) with k = -0.5, 0.5, 1.5, ...
	edges <- c(0, times[-1] - dt / 2, times[length(times)] + dt / 2)
	cdf_edges <- pgamma(edges, shape = shape, rate = rate)
	diff(cdf_edges)
}

#' Compute k_eff trajectory via deterministic convolutions
#'
#' For a given renewal-equation trajectory and punctuation level psi, computes
#' the time-varying effective dispersion parameter k_eff(t).
#'
#' @param ren_out  Output of renewal_epidemic() — tibble with columns t, j, S
#' @param alpha    Shape parameter of Gamma generation interval
#' @param beta     Rate parameter of Gamma generation interval
#' @param R0       Basic reproduction number
#' @param psi      Punctuation parameter (0 = spike, 1 = smooth)
#' @return tibble with columns: t, pbar, var_l, keff, D (on coarse dt=0.1 grid)
compute_keff_trajectory <- function(ren_out, alpha, beta, R0, psi) {

	dt_fine <- ren_out$t[2] - ren_out$t[1]
	times   <- ren_out$t
	nt      <- length(times)
	S_vec   <- ren_out$S

	# Truncate to where incidence is non-negligible (speeds up computation)
	j_max <- max(ren_out$j)
	i_end <- max(which(ren_out$j > 1e-8 * j_max))
	i_end <- min(i_end + round(10 / dt_fine), nt)  # pad 10 days

	# ------------------------------------------------------------------
	# Special case: psi = 1 (smooth) — all variation is within-individual,
	# no synchronisation penalty, k_eff = Inf, D = 1
	# ------------------------------------------------------------------
	if (psi > 1 - 1e-6) {
		# p_bar = convolution of S with full Gamma(alpha, beta)
		w_full <- gamma_weights(times, shape = alpha, rate = beta, dt = dt_fine)
		pbar <- numeric(i_end)
		for (i in 1:i_end) {
			# h(t_i) = sum_{k>=0} S(t_i + t_k) * w(t_k)
			k_max <- min(nt - i, nt - 1)
			if (k_max < 0) { pbar[i] <- S_vec[nt]; next }
			idx_s <- i:(i + k_max)
			pbar[i] <- sum(S_vec[idx_s] * w_full[1:(k_max + 1)])
		}
		out_idx <- seq(1, i_end, by = round(0.1 / dt_fine))
		return(tibble(
			t     = times[out_idx],
			pbar  = pbar[out_idx],
			var_l = 0,
			keff  = Inf,
			D     = 1
		))
	}

	# ------------------------------------------------------------------
	# General case: psi in [0, 1)
	# ------------------------------------------------------------------

	# Step 1: Compute h(s) = E_epsilon[S(s + epsilon)]
	#   epsilon ~ Gamma(psi*alpha, beta) — within-individual variation
	#   For psi = 0: epsilon = 0, so h(s) = S(s)
	if (psi < 1e-6) {
		h <- S_vec[1:i_end]
	} else {
		w_eps <- gamma_weights(times, shape = psi * alpha, rate = beta, dt = dt_fine)
		h <- numeric(i_end)
		for (i in 1:i_end) {
			k_max <- min(nt - i, nt - 1)
			if (k_max < 0) { h[i] <- S_vec[nt]; next }
			idx_s <- i:(i + k_max)
			h[i] <- sum(S_vec[idx_s] * w_eps[1:(k_max + 1)])
		}
	}

	# Step 2: Compute m1(t) = E_l[h(t+l)] and m2(t) = E_l[h(t+l)^2]
	#   l ~ Gamma((1-psi)*alpha, beta) — between-individual shift
	#   For psi = 0: l ~ Gamma(alpha, beta) — full generation interval as shift
	l_shape <- (1 - psi) * alpha
	w_l <- gamma_weights(times, shape = l_shape, rate = beta, dt = dt_fine)

	h_sq <- h^2
	m1 <- numeric(i_end)
	m2 <- numeric(i_end)

	for (i in 1:i_end) {
		k_max <- min(i_end - i, nt - 1)
		if (k_max < 0) {
			m1[i] <- h[i_end]
			m2[i] <- h_sq[i_end]
			next
		}
		idx_h <- i:(i + k_max)
		ww    <- w_l[1:(k_max + 1)]
		m1[i] <- sum(h[idx_h] * ww)
		m2[i] <- sum(h_sq[idx_h] * ww)
	}

	# Step 3: Var_l, k_eff, D
	var_l <- pmax(m2 - m1^2, 0)  # numerical floor at 0
	keff  <- ifelse(var_l > 0, m1^2 / var_l, Inf)
	D     <- 1 + R0 * var_l / pmax(m1, 1e-20)

	# Output on coarser grid
	out_idx <- seq(1, i_end, by = max(1, round(0.1 / dt_fine)))
	tibble(
		t     = times[out_idx],
		pbar  = m1[out_idx],
		var_l = var_l[out_idx],
		keff  = keff[out_idx],
		D     = D[out_idx]
	)
}


#' Compute incidence-weighted mean overdispersion index
#'
#' @param keff_df   Output of compute_keff_trajectory()
#' @param ren_out   Output of renewal_epidemic()
#' @return Scalar D_weighted = integral of j(t)*D(t) / integral of j(t)
compute_variance_ratio <- function(keff_df, ren_out) {
	# Interpolate deterministic incidence onto keff grid
	j_interp <- approx(ren_out$t, ren_out$j, xout = keff_df$t, rule = 2)$y
	dt <- keff_df$t[2] - keff_df$t[1]

	sum(j_interp * keff_df$D * dt) / sum(j_interp * dt)
}


# ==============================================================================
# 3. Main loop over pathogens
# ==============================================================================

keff_all     <- list()
varratio_all <- list()

for (pars in parslist) {

pathogen <- pars$pathogen
T_gen    <- pars$Tgen
alpha    <- pars$alpha
beta     <- pars$beta
R0       <- pars$R0

cat(sprintf("\n===== %s: T=%.2f, alpha=%.2f, R0=%.1f =====\n",
            pathogen, T_gen, alpha, R0))

# --------------------------------------------------------------------------
# 3a. Deterministic trajectory
# --------------------------------------------------------------------------

ren_out <- renewal_epidemic(R0, alpha, T_gen, popsize)

# --------------------------------------------------------------------------
# 3b. Compute k_eff(t) for each psi
# --------------------------------------------------------------------------

keff_list <- list()

for (psi in psivals) {
	cat(sprintf("  Computing k_eff for psi = %.2f ...\n", psi))
	kdf <- compute_keff_trajectory(ren_out, alpha, beta, R0, psi)
	kdf$psi <- psi
	keff_list[[as.character(psi)]] <- kdf

	# Variance ratio
	D_w <- compute_variance_ratio(kdf, ren_out)
	cat(sprintf("    D_weighted = %.4f\n", D_w))
}

keff_df <- bind_rows(keff_list) %>%
	mutate(psi = factor(psi))

keff_all[[pathogen]] <- keff_df

# --------------------------------------------------------------------------
# 3c. Variance ratio predictions
# --------------------------------------------------------------------------

D_weighted <- sapply(keff_list, function(kdf) {
	compute_variance_ratio(kdf, ren_out)
})
names(D_weighted) <- psivals

# Normalise to D_weighted(psi=1)
D_ref <- D_weighted[as.character(1)]
varratio_theory <- D_weighted / D_ref

varratio_all[[pathogen]] <- tibble(
	pathogen = pathogen,
	psi      = as.numeric(names(varratio_theory)),
	D_weighted    = as.numeric(D_weighted),
	varratio_pred = as.numeric(varratio_theory)
)

cat(sprintf("  Variance ratios (relative to psi=1):\n"))
print(varratio_all[[pathogen]])

# --------------------------------------------------------------------------
# 3d. Empirical final size variance from cached simulations
# --------------------------------------------------------------------------

# Load cached simulations (psi values are those from episims_gamma, not psivals)
sim_psivals <- c(0, 0.5, 1)
cuminf_df_raw <- load_cache(pathogen, nsim, popsize, sim_psivals)

if (!is.null(cuminf_df_raw)) {
	cuminf_df <- cuminf_df_raw

	fs_df <- cuminf_df %>%
		filter(established == 1) %>%
		group_by(sim, psi) %>%
		summarise(finalsize = max(cuminf), .groups = "drop") %>%
		group_by(psi) %>%
		summarise(fs_mean = mean(finalsize),
		          fs_var  = var(finalsize),
		          .groups = "drop")

	fs_var_ref <- fs_df %>% filter(psi == 1) %>% pull(fs_var)
	fs_df$varratio_emp <- fs_df$fs_var / fs_var_ref
	fs_df$pathogen <- pathogen

	varratio_all[[pathogen]] <- varratio_all[[pathogen]] %>%
		left_join(fs_df %>% select(psi, fs_var, varratio_emp),
		          by = "psi")

	cat(sprintf("  Empirical variance ratios:\n"))
	print(fs_df %>% select(psi, fs_var, varratio_emp))
}

# --------------------------------------------------------------------------
# 3e. Figures
# --------------------------------------------------------------------------

# Figure 1: k_eff(t) over time (exclude psi=1 which is Inf)
keff_plot <- keff_df %>%
	filter(psi != 1, is.finite(keff), keff > 0) %>%
	ggplot(aes(x = t, y = keff, col = psi)) +
	geom_line(linewidth = 0.8, alpha = 0.8) +
	scale_y_log10() +
	scale_color_manual(values = psi_colors) +
	labs(x = "Days", y = expression(k[eff](t)),
	     col = expression(psi),
	     title = pathogen) +
	theme_classic()

save_fig(keff_plot, paste0("fig_keff_time_", pathogen))

# Figure 2: D(t) = overdispersion index over time
D_plot <- keff_df %>%
	ggplot(aes(x = t, y = D, col = psi)) +
	geom_line(linewidth = 0.8, alpha = 0.8) +
	scale_color_manual(values = psi_colors) +
	labs(x = "Days", y = "D(t) = Var(Z) / E[Z]",
	     col = expression(psi),
	     title = pathogen) +
	theme_classic()

save_fig(D_plot, paste0("fig_D_time_", pathogen))

cat(sprintf("  %s: k_eff and D figures saved.\n", pathogen))

} # end pathogen loop


# ==============================================================================
# 4. Cross-pathogen variance ratio comparison figure
# ==============================================================================

varratio_combined <- bind_rows(varratio_all)

# Theory: available for all psi values
# Empirical: only for psi in {0, 0.5, 1} (from simulations)
fig_varratio <- ggplot() +
	# Theory as lines
	geom_line(data = varratio_combined,
	          aes(x = psi, y = varratio_pred, col = pathogen),
	          linewidth = 0.8) +
	geom_point(data = varratio_combined,
	           aes(x = psi, y = varratio_pred, col = pathogen),
	           size = 2) +
	# Empirical as open circles (where available)
	geom_point(data = varratio_combined %>% filter(!is.na(varratio_emp)),
	           aes(x = psi, y = varratio_emp, col = pathogen),
	           shape = 1, size = 3, stroke = 1.2) +
	geom_hline(yintercept = 1, lty = "dashed", col = "grey50") +
	scale_x_continuous(breaks = psivals) +
	labs(x = expression(psi),
	     y = expression("Var(final size) / Var(final size)"[psi == 1]),
	     col = "Pathogen",
	     title = "Final size variance ratio: theory (filled) vs simulation (open)") +
	theme_classic()

save_fig(fig_varratio, "fig_variance_ratio")
cat("\nVariance ratio comparison figure saved.\n")

cat("\n===== Summary =====\n")
print(varratio_combined %>% select(pathogen, psi, D_weighted, varratio_pred, varratio_emp))
