library(tidyverse)
source("code/utils.R")
source("code/global_parameters.R")
source("code/parameters.R")

# ==============================================================================
# Theoretical survival curves via renewal equation + time-shift approximation
#
# For each pathogen and each psi value, computes the distribution of the
# stochastic time-shift variable W from the branching-process limit theorem,
# then overlays theoretical survival curves on the empirical ones from
# episims_gamma.R.
#
# Requires cached simulation output (generated by episims_gamma.R).
#
# Theory reference: notes/findings_uncontrolled.md
# ==============================================================================

# ==============================================================================
# 0. Parameters
# ==============================================================================

n_draws   <- 100000 # for the theoretical distributions
psivals   <- c(0, 0.5, 1)
psi_colors <- c("0" = "red", "0.5" = "blue", "1" = "black")

set.seed(42)

# ==============================================================================
# 1. Helper functions
# ==============================================================================

#' Compute Var(W) for Gamma generation interval with punctuation psi
#'
#' Uses the rho_1/rho_2 parameterization from the writeup:
#'   z = R0^(1/alpha) - 1
#'   rho_k = (1+z)^k / (1+2z)
#'   Var(W) = (rho_1^alpha + rho_2^((1-psi)*alpha) - 1) / (1 - rho_1^alpha)
#'
#' @param R0    Basic reproduction number
#' @param alpha Shape parameter of Gamma generation interval
#' @param beta  Rate parameter of Gamma generation interval
#' @param r     Malthusian growth rate
#' @param psi   Punctuation parameter (0 = spike, 1 = smooth)
compute_var_W <- function(R0, alpha, beta, r, psi) {
	z <- R0^(1 / alpha) - 1
	rho_1 <- (1 + z) / (1 + 2 * z)
	rho_2 <- (1 + z)^2 / (1 + 2 * z)

	rho_1_a <- rho_1^alpha
	(rho_1_a + rho_2^((1 - psi) * alpha) - 1) / (1 - rho_1_a)
}

#' Fit 2-moment Gamma to W | survival and return shape/rate
#'
#' Unconditional: E[W] = 1, E[W^2] = 1 + CV^2(W)
#' Conditional on survival (W > 0): E_cond = 1/(1-q), Var_cond from above
fit_W_gamma <- function(R0, alpha, beta, r, psi) {
	q <- extinction_prob(R0)
	var_W <- compute_var_W(R0, alpha, beta, r, psi)
	EW2 <- 1 + var_W  # E[W^2] = Var(W) + (E[W])^2 = Var(W) + 1

	E_cond   <- 1 / (1 - q)
	E2_cond  <- EW2 / (1 - q)
	var_cond <- E2_cond - E_cond^2

	list(
		shape = E_cond^2 / var_cond,
		rate  = E_cond   / var_cond,
		E_cond = E_cond,
		var_cond = var_cond,
		var_W = var_W,
		q = q
	)
}

# ==============================================================================
# 3. Loop over pathogens
# ==============================================================================

for (pars in parslist) {

pathogen <- pars$pathogen
Tgen     <- pars$Tgen
alpha    <- pars$alpha
beta     <- pars$beta
R0       <- pars$R0
r        <- pars$r

cat(sprintf("\n===== %s: Tgen=%.2f, alpha=%.2f, R0=%.1f =====\n",
            pathogen, Tgen, alpha, R0))

# --------------------------------------------------------------------------
# 3b. Deterministic time to threshold from renewal equation
# --------------------------------------------------------------------------

ren_out <- renewal_epidemic(R0, alpha, Tgen, popsize)

t_det <- approx(
	x = ren_out$cuminf * popsize,
	y = ren_out$t,
	xout = establishment_threshold,
	ties = mean
)$y

# --------------------------------------------------------------------------
# 3c. Theoretical W distributions and survival curves for each psi
# --------------------------------------------------------------------------

theory_surv_list_g  <- list()

for (psi in psivals) {

	# Compute 2-moment Gamma
	fit_g <- fit_W_gamma(R0, alpha, beta, r, psi)

	# Sample W | survival from fitted 2-moment Gamma
	W_g <- rgamma(n_draws, shape = fit_g$shape, rate = fit_g$rate)
	t_stoch_g <- t_det - log(W_g) / r

	theory_surv_list_g[[as.character(psi)]] <- tibble(
		psi = factor(psi), t_stoch = t_stoch_g)
}

theory_draws_g_df  <- bind_rows(theory_surv_list_g)

# --------------------------------------------------------------------------
# 3d. Load empirical simulation data and build empirical survival curves
# --------------------------------------------------------------------------

cache <- load_cache(pathogen, nsim, popsize, psivals)

if (is.null(cache)) {
	cat(sprintf("  WARNING: cache not found for %s (n=%d, s=%d), skipping\n",
	    pathogen, popsize, nsim))
	next
}

# Extract time to establishment from summary (pre-computed in episims_gamma.R)
time_to_establishment <- cache$summary %>%
	filter(established == 1, !is.na(establishment_time)) %>%
	transmute(sim, psi, tinf = establishment_time)

# Build empirical survival curves
t_max <- max(time_to_establishment$tinf)
t_grid <- seq(0, t_max, length.out = 500)

empirical_surv <- time_to_establishment %>%
	group_by(psi) %>%
	summarise(
		t = list(t_grid),
		prop_below = list(sapply(t_grid, function(tt) mean(tinf > tt))),
		.groups = "drop") %>%
	unnest(cols = c(t, prop_below))

# Build theoretical survival curves on the same grid (2-moment gamma)
theory_surv_g <- theory_draws_g_df %>%
	group_by(psi) %>%
	summarise(
		t = list(t_grid),
		prop_below = list(sapply(t_grid, function(tt) mean(t_stoch > tt))),
		.groups = "drop") %>%
	unnest(cols = c(t, prop_below))

# --------------------------------------------------------------------------
# 3e. Overlay figures
# --------------------------------------------------------------------------

breakvals <- if (t_max > 120) seq(0, 365, by = 15) else seq(0, 365, by = 7)
surv_ylab <- paste0("Proportion not yet reaching ", establishment_threshold, " cases")

# 2-moment gamma theory overlay
fig_survival <- ggplot() +
	geom_line(data = empirical_surv,
	          aes(x = t, y = prop_below, col = psi),
	          alpha = 0.6, linewidth = 0.8) +
	geom_line(data = theory_surv_g,
	          aes(x = t, y = prop_below, col = psi),
	          linetype = "dashed", linewidth = 0.8) +
	scale_x_continuous(breaks = breakvals) +
	scale_color_manual(values = psi_colors) +
	labs(x = "Days", y = surv_ylab, col = expression(psi),
	     title = paste0(pathogen)) +
	theme_classic()

save_fig(fig_survival, paste0("fig_survival_v2_", pathogen))

# Output the survival at weekly intervals: 
empirical_surv_summary <- empirical_surv %>% 
	mutate(week=floor(t/7)) %>% 
	group_by(week) %>% 
	filter(t==max(t))
print(empirical_surv_summary, n=Inf)

# Output the time each curve takes to reach 5% survival: 
empirical_surv_summary_pct <- empirical_surv %>% 
	filter(prop_below < 0.05) %>% 
	group_by(psi) %>% 
	slice(1) 
print(empirical_surv_summary, n=Inf)

# Find the date of the max deviation between psi=0 and psi=1 survival curves:
empirical_surv_summary_max <- empirical_surv %>% 
	filter(psi %in% c(0,1)) %>% 
	mutate(day=floor(t)) %>% 
	group_by(psi, day) %>% 
	summarise(prop_below=max(prop_below)) %>% 
	pivot_wider(names_from=psi, values_from=prop_below) %>% 
	mutate(diff=abs(`1`-`0`)) %>% 
	filter(diff==max(diff))

cat(sprintf("  %s: Day of max difference.\n", pathogen))
print(empirical_surv_summary_max, n=Inf)

cat(sprintf("  %s: theory overlays saved (GG + Gamma).\n", pathogen))

# --------------------------------------------------------------------------
# 3f. W distribution: empirical histogram with moment-matched Gamma overlay
# --------------------------------------------------------------------------

# Empirical W | survival: W = exp(r * (t_det - t_emp))
W_empirical <- time_to_establishment %>%
	mutate(W = exp(r * (t_det - tinf)))

# Theoretical density functions for each psi
W_density_list <- list()
w_grid <- seq(1e-4, quantile(W_empirical$W, 0.995), length.out = 500)

for (psi in psivals) {
	fit_g  <- fit_W_gamma(R0, alpha, beta, r, psi)

	# Gamma density
	d_g <- dgamma(w_grid, shape = fit_g$shape, rate = fit_g$rate)

	W_density_list[[as.character(psi)]] <- tibble(
		psi = factor(psi), w = w_grid,
		Gamma = d_g) %>%
		pivot_longer(cols = c(Gamma),
		             names_to = "fit", values_to = "density")
}

W_density_df <- bind_rows(W_density_list)

fig_W_hist <- ggplot(W_empirical, aes(x = W)) +
	geom_histogram(aes(y = after_stat(density)), bins = 60,
	               fill = "white", col = "darkgrey") +
	geom_line(data = W_density_df,
	          aes(x = w, y = density, col = fit, linetype = fit),
	          linewidth = 0.8) +
	scale_color_manual(values = c("Gamma" = "blue", "Gen. Gamma" = "red")) +
	scale_linetype_manual(values = c("Gamma" = "dashed", "Gen. Gamma" = "solid")) +
	facet_wrap(~psi, nrow = 1, scales = "free_y",
	           labeller = label_bquote(psi == .(as.numeric(as.character(psi))))) +
	labs(x = "W | survival", y = "Density",
	     col = "Fit", linetype = "Fit",
	     title = pathogen) +
	theme_classic() +
	theme(legend.position = "bottom")

save_fig(fig_W_hist, paste0("fig_W_hist_", pathogen))

cat(sprintf("  %s: W histogram saved.\n", pathogen))

# --------------------------------------------------------------------------
# 3g. Overlaid W distributions by psi
# --------------------------------------------------------------------------

fig_W_overlay <- ggplot() +
	geom_histogram(data = W_empirical,
	               aes(x = W, y = after_stat(density), fill = psi),
	               bins = 60, alpha = 0.25, position = "identity") +
	geom_line(data = W_density_df,
	          aes(x = w, y = density, col = psi),
	          linewidth = 0.8) +
	scale_fill_manual(values = psi_colors) +
	scale_color_manual(values = psi_colors) +
	scale_x_continuous(limits=c(0, 5)) + 
	scale_y_continuous(limits=c(0, 1.5)) + 
	labs(x = "W | survival", y = "Density",
	     col = expression(psi), fill = expression(psi),
	     title = pathogen) +
	theme_classic()

save_fig(fig_W_overlay, paste0("fig_W_overlay_", pathogen))

cat(sprintf("  %s: W overlay saved.\n", pathogen))

# --------------------------------------------------------------------------
# 3h. Overlaid varsigma distributions by psi
# --------------------------------------------------------------------------

# Empirical varsigma = log(W) / r
varsigma_empirical <- W_empirical %>%
	mutate(varsigma = log(W) / r)

# Theoretical density of varsigma = log(W)/r where W ~ Gamma(k, lambda):
#   f_varsigma(s) = f_W(e^{rs}) * r * e^{rs}
varsigma_density_list <- list()
s_grid <- seq(
	quantile(varsigma_empirical$varsigma, 0.005),
	quantile(varsigma_empirical$varsigma, 0.995),
	length.out = 500)

for (psi in psivals) {
	fit_g <- fit_W_gamma(R0, alpha, beta, r, psi)
	w_vals <- exp(r * s_grid)
	d_s <- dgamma(w_vals, shape = fit_g$shape, rate = fit_g$rate) * r * w_vals

	varsigma_density_list[[as.character(psi)]] <- tibble(
		psi = factor(psi), s = s_grid, density = d_s)
}

varsigma_density_df <- bind_rows(varsigma_density_list)

# Compute empirical and theoretical means of varsigma by psi
varsigma_emp_means <- varsigma_empirical %>%
	group_by(psi) %>%
	summarise(mean_varsigma = mean(varsigma), .groups = "drop")

varsigma_theo_means <- tibble(
	psi = factor(psivals),
	mean_varsigma = sapply(psivals, function(p) {
		fit_g <- fit_W_gamma(R0, alpha, beta, r, p)
		(digamma(fit_g$shape) - log(fit_g$rate)) / r
	}))

fig_varsigma_overlay <- ggplot() +
	geom_histogram(data = varsigma_empirical,
	               aes(x = varsigma, y = after_stat(density), fill = psi),
	               bins = 60, alpha = 0.25, position = "identity") +
	geom_line(data = varsigma_density_df,
	          aes(x = s, y = density, col = psi),
	          linewidth = 0.8) +
	geom_vline(data = varsigma_emp_means,
	           aes(xintercept = mean_varsigma, col = psi),
	           linetype = "dashed", linewidth = 0.6) +
	geom_vline(data = varsigma_theo_means,
	           aes(xintercept = mean_varsigma, col = psi),
	           linetype = "solid", linewidth = 0.6) +
	scale_fill_manual(values = psi_colors) +
	scale_color_manual(values = psi_colors) +
	labs(x = expression(varsigma ~~ "(days)"), y = "Density",
	     col = expression(psi), fill = expression(psi),
	     title = pathogen) +
	theme_classic()

save_fig(fig_varsigma_overlay, paste0("fig_varsigma_overlay_", pathogen))

cat(sprintf("  %s: varsigma overlay saved.\n", pathogen))

} # end pathogen loop

# # ==============================================================================
# # 4. Var(W) and E[varsigma] +/- SD[varsigma] as functions of psi
# # ==============================================================================

# psi_grid <- seq(0, 1, length.out = 201)

# theory_curves <- map_dfr(parslist, function(pars) {
# 	R0 <- pars$R0; alpha <- pars$alpha; beta <- pars$beta; r <- pars$r

# 	tibble(
# 		pathogen = pars$pathogen,
# 		psi = psi_grid,
# 		var_W = sapply(psi_grid, function(p)
# 			compute_var_W(R0, alpha, beta, r, p))
# 	) %>% mutate(
# 		# Gamma shape k for W|surv, using k = (1 - c^alpha) / (c^alpha + p*sigma^((1-psi)*alpha) - 1)
# 		k = {
# 			fit <- sapply(psi_grid, function(p) fit_W_gamma(R0, alpha, beta, r, p)$shape)
# 			fit
# 		},
# 		E_varsigma  = (digamma(k) - log(k) + log(1 / (1 - extinction_prob(R0)))) / r,
# 		SD_varsigma = sqrt(trigamma(k)) / r
# 	)
# })

# # --- Var(W) vs psi ---
# fig_var_W <- ggplot(theory_curves, aes(x = psi, y = var_W, col = pathogen)) +
# 	geom_line(linewidth = 0.8) +
# 	labs(x = expression(psi), y = expression(Var(W)), col = "Pathogen") +
# 	theme_classic()

# save_fig(fig_var_W, "fig_var_W_vs_psi")

# # --- E[varsigma] +/- SD[varsigma] vs psi ---
# fig_E_varsigma <- ggplot(theory_curves, aes(x = psi, col = pathogen, fill = pathogen)) +
# 	geom_ribbon(aes(ymin = E_varsigma - SD_varsigma,
# 	                 ymax = E_varsigma + SD_varsigma),
# 	            alpha = 0.15, colour = NA) +
# 	geom_line(aes(y = E_varsigma), linewidth = 0.8) +
# 	labs(x = expression(psi),
# 	     y = expression(E(varsigma) %+-% SD(varsigma) ~~ "(days)"),
# 	     col = "Pathogen", fill = "Pathogen") +
# 	theme_classic()

# save_fig(fig_E_varsigma, "fig_E_varsigma_vs_psi")

# cat("Var(W) and E[varsigma] vs psi figures saved.\n")
