library(tidyverse)
source("code/utils.R")
source("code/parameters.R")

# ==============================================================================
# Theoretical survival curves via renewal equation + time-shift approximation
#
# For each pathogen and each psi value, computes the distribution of the
# stochastic time-shift variable W from the branching-process limit theorem,
# then overlays theoretical survival curves on the empirical ones from
# episims_gamma.R.
#
# Requires cached simulation output in output/cuminf_df_{pathogen}_n{popsize}_s{nsim}.csv
# (generated by episims_gamma.R).
#
# Theory reference: notes/findings_uncontrolled.md
# ==============================================================================

# ==============================================================================
# 1. Helper functions
# ==============================================================================

#' Extinction probability for a Poisson(R0) branching process
extinction_prob <- function(R0) {
	if (R0 <= 1) return(1)
	q <- 0.5
	for (i in 1:1000) {
		q_new <- exp(R0 * (q - 1))
		if (abs(q_new - q) < 1e-12) break
		q <- q_new
	}
	q
}

#' Compute Var(S) for Gamma generation interval with punctuation psi
#'
#' S = sum_j e^{-r * tau_j} where tau_j = l_i + epsilon_j
#' Var(S) = m2 + R0^2 * rho^(2*psi*alpha) * [rho2^((1-psi)*alpha) - rho^(2*(1-psi)*alpha)]
#'
#' @param R0    Basic reproduction number
#' @param alpha Shape parameter of Gamma generation interval
#' @param beta  Rate parameter of Gamma generation interval
#' @param r     Malthusian growth rate
#' @param psi   Punctuation parameter (0 = spike, 1 = smooth)
compute_var_S <- function(R0, alpha, beta, r, psi) {
	rho  <- beta / (beta + r)
	rho2 <- beta / (beta + 2 * r)

	# m2: psi-independent
	m2 <- R0 * rho2^alpha

	# Synchronisation penalty (vanishes at psi = 1)
	sync <- R0^2 * rho^(2 * psi * alpha) *
		(rho2^((1 - psi) * alpha) - rho^(2 * (1 - psi) * alpha))

	m2 + sync
}

#' Compute CV^2(W) = Var(S) / (1 - m2)
compute_CV2_W <- function(R0, alpha, beta, r, psi) {
	rho2 <- beta / (beta + 2 * r)
	m2 <- R0 * rho2^alpha
	var_S <- compute_var_S(R0, alpha, beta, r, psi)
	var_S / (1 - m2)
}

#' Fit 2-moment Gamma to W | survival and return shape/rate
#'
#' Unconditional: E[W] = 1, E[W^2] = 1 + CV^2(W)
#' Conditional on survival (W > 0): E_cond = 1/(1-q), Var_cond from above
fit_W_gamma <- function(R0, alpha, beta, r, psi) {
	q <- extinction_prob(R0)
	CV2 <- compute_CV2_W(R0, alpha, beta, r, psi)
	EW2 <- 1 + CV2

	E_cond   <- 1 / (1 - q)
	E2_cond  <- EW2 / (1 - q)
	var_cond <- E2_cond - E_cond^2

	list(
		shape = E_cond^2 / var_cond,
		rate  = E_cond   / var_cond,
		E_cond = E_cond,
		var_cond = var_cond,
		CV2 = CV2,
		q = q
	)
}

#' Compute E[W^1] through E[W^n_moments] for the time-shift variable W
#'
#' Uses the compound Poisson moment recursion with hard-coded Bell polynomial
#' coefficients for n <= 5.
#'
#' @param R0        Basic reproduction number
#' @param alpha     Shape parameter of Gamma generation interval
#' @param beta      Rate parameter of Gamma generation interval
#' @param r         Malthusian growth rate
#' @param psi       Punctuation parameter (0 = spike, 1 = smooth)
#' @param n_moments Number of moments to compute (max 5)
#' @return Named numeric vector of unconditional moments (m_1, ..., m_n)
compute_W_moments <- function(R0, alpha, beta, r, psi, n_moments = 5) {
	stopifnot(n_moments >= 1, n_moments <= 5)

	# rho_k = beta / (beta + k*r)
	rho <- sapply(1:n_moments, function(k) beta / (beta + k * r))

	# Cumulants of the inner sum Y: kappa_k = R0 * rho_k^(psi*alpha) * m_k
	# m_1 = 1 (unconditional mean of W)
	m <- numeric(n_moments)
	m[1] <- 1

	# For n >= 2: m_n = rho_n^((1-psi)*alpha) * D_n / (1 - R0 * rho_n^alpha)
	# where D_n = B_n(kappa_1, ..., kappa_{n-1}, 0)
	# and kappa_k = R0 * rho_k^(psi*alpha) * m_k

	if (n_moments >= 2) {
		k1 <- R0 * rho[1]^(psi * alpha) * m[1]

		# D_2 = k1^2
		D2 <- k1^2
		m[2] <- rho[2]^((1 - psi) * alpha) * D2 / (1 - R0 * rho[2]^alpha)
	}

	if (n_moments >= 3) {
		k2 <- R0 * rho[2]^(psi * alpha) * m[2]

		# D_3 = k1^3 + 3*k1*k2
		D3 <- k1^3 + 3 * k1 * k2
		m[3] <- rho[3]^((1 - psi) * alpha) * D3 / (1 - R0 * rho[3]^alpha)
	}

	if (n_moments >= 4) {
		k3 <- R0 * rho[3]^(psi * alpha) * m[3]

		# D_4 = k1^4 + 6*k1^2*k2 + 4*k1*k3 + 3*k2^2
		D4 <- k1^4 + 6 * k1^2 * k2 + 4 * k1 * k3 + 3 * k2^2
		m[4] <- rho[4]^((1 - psi) * alpha) * D4 / (1 - R0 * rho[4]^alpha)
	}

	if (n_moments >= 5) {
		k4 <- R0 * rho[4]^(psi * alpha) * m[4]

		# D_5 = k1^5 + 10*k1^3*k2 + 10*k1^2*k3 + 15*k1*k2^2 + 5*k1*k4 + 10*k2*k3
		D5 <- k1^5 + 10 * k1^3 * k2 + 10 * k1^2 * k3 +
			15 * k1 * k2^2 + 5 * k1 * k4 + 10 * k2 * k3
		m[5] <- rho[5]^((1 - psi) * alpha) * D5 / (1 - R0 * rho[5]^alpha)
	}

	names(m) <- paste0("m", 1:n_moments)
	m
}

#' Fit 3-parameter generalized gamma to W | survival using 5-moment matching
#'
#' GG(beta_gg, a1, a2) has k-th moment:
#'   M_k = beta_gg^k * Gamma((a1+k)/a2) / Gamma(a1/a2)
#'
#' Fit by minimizing sum of squared standardized moment errors.
#'
#' @param R0    Basic reproduction number
#' @param alpha Shape parameter of Gamma generation interval
#' @param beta  Rate parameter of Gamma generation interval
#' @param r     Malthusian growth rate
#' @param psi   Punctuation parameter
#' @return List with beta_gg, a1, a2, moments, cond_moments, q
fit_W_gengamma <- function(R0, alpha, beta, r, psi) {
	# Unconditional moments
	m <- compute_W_moments(R0, alpha, beta, r, psi, n_moments = 5)

	# Extinction probability and conditional moments
	q <- extinction_prob(R0)
	cond_m <- m / (1 - q)

	# Standardization weights
	eta <- log10(cond_m)

	# GG k-th moment: beta_gg^k * Gamma((a1+k)/a2) / Gamma(a1/a2)
	gg_moments <- function(beta_gg, a1, a2) {
		log_base <- lgamma(a1 / a2)
		sapply(1:5, function(k) {
			beta_gg^k * exp(lgamma((a1 + k) / a2) - log_base)
		})
	}

	# Loss function: sum of squared standardized errors
	loss <- function(par) {
		beta_gg <- par[1]
		a1 <- par[2]
		a2 <- par[3]
		if (beta_gg <= 0 || a1 <= 0 || a2 <= 0) return(1e20)
		M <- tryCatch(gg_moments(beta_gg, a1, a2), error = function(e) rep(NA, 5))
		if (any(is.na(M)) || any(M <= 0)) return(1e20)
		sum(((cond_m - M) / 10^eta)^2)
	}

	# Optimize on log scale for better conditioning
	loss_log <- function(logpar) {
		loss(exp(logpar))
	}

	# Starting values from 2-moment Gamma fit (a2 = 1 recovers ordinary Gamma)
	E_cond <- cond_m[1]
	E2_cond <- cond_m[2]
	var_cond <- E2_cond - E_cond^2
	shape0 <- E_cond^2 / var_cond
	rate0 <- E_cond / var_cond
	beta_gg0 <- 1 / rate0
	a1_0 <- shape0

	# Multi-start: try several a2 values to avoid local minima
	best <- list(value = Inf)
	for (a2_start in c(0.5, 0.75, 1.0, 1.5, 2.0)) {
		fit <- tryCatch(
			optim(
				par = log(c(beta_gg0, a1_0, a2_start)),
				fn = loss_log,
				method = "Nelder-Mead",
				control = list(maxit = 5000)
			),
			error = function(e) list(value = Inf)
		)
		if (fit$value < best$value) best <- fit
	}

	par <- exp(best$par)
	list(
		beta_gg = par[1],
		a1 = par[2],
		a2 = par[3],
		moments = m,
		cond_moments = cond_m,
		q = q,
		convergence = best$convergence,
		loss = best$value
	)
}

# ==============================================================================
# 2. Global parameters
# ==============================================================================

popsize   <- 1000
nsim      <- 1000
threshold <- 100
n_draws   <- 100000
psivals   <- c(0, 0.5, 1)
psi_colors <- c("0" = "red", "0.5" = "blue", "1" = "black")

set.seed(42)

# ==============================================================================
# 3. Loop over pathogens
# ==============================================================================

for (pars in parslist) {

pathogen <- pars$pathogen
T        <- pars$Tgen
alpha    <- pars$alpha
beta     <- pars$beta
R0       <- pars$R0

cat(sprintf("\n===== %s: T=%.2f, alpha=%.2f, R0=%.1f =====\n",
            pathogen, T, alpha, R0))

# --------------------------------------------------------------------------
# 3a. Malthusian growth rate
# --------------------------------------------------------------------------

r_malthusian <- uniroot(
	function(r) R0 * (beta / (beta + r))^alpha - 1,
	interval = c(0, 10))$root

cat(sprintf("  r_malthusian = %.6f\n", r_malthusian))

# --------------------------------------------------------------------------
# 3b. Deterministic time to threshold from renewal equation
# --------------------------------------------------------------------------

ren_out <- renewal_epidemic(R0, alpha, T, popsize)

t_det <- approx(
	x = ren_out$cuminf * popsize,
	y = ren_out$t,
	xout = threshold,
	ties = mean
)$y

cat(sprintf("  Deterministic time to %d cases: %.2f days\n", threshold, t_det))

# --------------------------------------------------------------------------
# 3c. Theoretical W distributions and survival curves for each psi
# --------------------------------------------------------------------------

theory_surv_list <- list()

for (psi in psivals) {
	# Fit generalized gamma via 5-moment matching
	fit_gg <- fit_W_gengamma(R0, alpha, beta, r_malthusian, psi)

	# Also compute 2-moment Gamma for comparison
	fit_g <- fit_W_gamma(R0, alpha, beta, r_malthusian, psi)

	cat(sprintf("  psi=%.1f: Gamma(shape=%.3f, rate=%.3f) | GG(beta=%.4f, a1=%.4f, a2=%.4f) loss=%.2e\n",
	            psi, fit_g$shape, fit_g$rate,
	            fit_gg$beta_gg, fit_gg$a1, fit_gg$a2, fit_gg$loss))

	# Sample W | survival from fitted generalized gamma
	# W* = beta_gg * Gamma(a1/a2, 1)^(1/a2)
	W <- fit_gg$beta_gg * rgamma(n_draws, shape = fit_gg$a1 / fit_gg$a2, rate = 1)^(1 / fit_gg$a2)

	# Time shift: tau = log(W) / r
	tau <- log(W) / r_malthusian

	# Stochastic time to threshold = deterministic time - tau
	t_stoch <- t_det - tau

	theory_surv_list[[as.character(psi)]] <- tibble(
		psi = factor(psi),
		t_stoch = t_stoch
	)
}

theory_draws_df <- bind_rows(theory_surv_list)

# --------------------------------------------------------------------------
# 3d. Load empirical simulation data and build empirical survival curves
# --------------------------------------------------------------------------

cuminf_df <- load_cache(pathogen, nsim, popsize, psivals)

if (is.null(cuminf_df)) {
	cat(sprintf("  WARNING: cache not found for %s (n=%d, s=%d), skipping\n",
	    pathogen, popsize, nsim))
	next
}

# Extract time to threshold for each established epidemic
time_to_threshold <- cuminf_df %>%
	filter(established == 1) %>%
	group_by(sim, psi) %>%
	filter(cuminf >= threshold) %>%
	slice(1) %>%
	ungroup() %>%
	select(sim, psi, tinf)

# Build empirical survival curves
t_max <- max(time_to_threshold$tinf)
t_grid <- seq(0, t_max, length.out = 500)

empirical_surv <- time_to_threshold %>%
	group_by(psi) %>%
	summarise(
		t = list(t_grid),
		prop_below = list(sapply(t_grid, function(tt) mean(tinf > tt))),
		.groups = "drop") %>%
	unnest(cols = c(t, prop_below))

# Build theoretical survival curves on the same grid
theory_surv <- theory_draws_df %>%
	group_by(psi) %>%
	summarise(
		t = list(t_grid),
		prop_below = list(sapply(t_grid, function(tt) mean(t_stoch > tt))),
		.groups = "drop") %>%
	unnest(cols = c(t, prop_below))

# --------------------------------------------------------------------------
# 3e. Overlay figure
# --------------------------------------------------------------------------

breakvals <- if (t_max > 120) seq(0, 365, by = 15) else seq(0, 365, by = 7)

fig_survival_theory <- ggplot() +
	# Empirical (solid)
	geom_line(data = empirical_surv,
	          aes(x = t, y = prop_below, col = psi),
	          alpha = 0.6, linewidth = 0.8) +
	# Theoretical (dashed)
	geom_line(data = theory_surv,
	          aes(x = t, y = prop_below, col = psi),
	          linetype = "dashed", linewidth = 0.8) +
	scale_x_continuous(breaks = breakvals) +
	scale_color_manual(values = psi_colors) +
	labs(x = "Days",
	     y = paste0("Proportion not yet reaching ", threshold, " cases"),
	     col = expression(psi),
	     title = pathogen) +
	theme_classic()

save_fig(fig_survival_theory, paste0("fig_survival_100_theory_", pathogen))

cat(sprintf("  %s: theory overlay saved.\n", pathogen))

} # end pathogen loop
