library(tidyverse)
source("code/utils.R")
source("code/parameters.R")

# ==============================================================================
# Theoretical survival curves via renewal equation + time-shift approximation
#
# For each pathogen and each psi value, computes the distribution of the
# stochastic time-shift variable W from the branching-process limit theorem,
# then overlays theoretical survival curves on the empirical ones from
# episims_gamma.R.
#
# Requires cached simulation output in output/cuminf_df_{pathogen}_n{popsize}_s{nsim}.csv
# (generated by episims_gamma.R).
#
# Theory reference: notes/findings_uncontrolled.md
# ==============================================================================

# ==============================================================================
# 1. Helper functions
# ==============================================================================

#' Compute Var(W) for Gamma generation interval with punctuation psi
#'
#' Uses the rho_1/rho_2 parameterization from the writeup:
#'   z = R0^(1/alpha) - 1
#'   rho_k = (1+z)^k / (1+2z)
#'   Var(W) = (rho_1^alpha + rho_2^((1-psi)*alpha) - 1) / (1 - rho_1^alpha)
#'
#' @param R0    Basic reproduction number
#' @param alpha Shape parameter of Gamma generation interval
#' @param beta  Rate parameter of Gamma generation interval
#' @param r     Malthusian growth rate
#' @param psi   Punctuation parameter (0 = spike, 1 = smooth)
compute_var_W <- function(R0, alpha, beta, r, psi) {
	z <- R0^(1 / alpha) - 1
	rho_1 <- (1 + z) / (1 + 2 * z)
	rho_2 <- (1 + z)^2 / (1 + 2 * z)

	rho_1_a <- rho_1^alpha
	(rho_1_a + rho_2^((1 - psi) * alpha) - 1) / (1 - rho_1_a)
}

#' Fit 2-moment Gamma to W | survival and return shape/rate
#'
#' Unconditional: E[W] = 1, E[W^2] = 1 + CV^2(W)
#' Conditional on survival (W > 0): E_cond = 1/(1-q), Var_cond from above
fit_W_gamma <- function(R0, alpha, beta, r, psi) {
	q <- extinction_prob(R0)
	var_W <- compute_var_W(R0, alpha, beta, r, psi)
	EW2 <- 1 + var_W  # E[W^2] = Var(W) + (E[W])^2 = Var(W) + 1

	E_cond   <- 1 / (1 - q)
	E2_cond  <- EW2 / (1 - q)
	var_cond <- E2_cond - E_cond^2

	list(
		shape = E_cond^2 / var_cond,
		rate  = E_cond   / var_cond,
		E_cond = E_cond,
		var_cond = var_cond,
		var_W = var_W,
		q = q
	)
}

#' Compute E[W^1] through E[W^n_moments] for the time-shift variable W
#'
#' Uses the compound Poisson moment recursion with hard-coded Bell polynomial
#' coefficients for n <= 5.
#'
#' @param R0        Basic reproduction number
#' @param alpha     Shape parameter of Gamma generation interval
#' @param beta      Rate parameter of Gamma generation interval
#' @param r         Malthusian growth rate
#' @param psi       Punctuation parameter (0 = spike, 1 = smooth)
#' @param n_moments Number of moments to compute (max 5)
#' @return Named numeric vector of unconditional moments (m_1, ..., m_n)
compute_W_moments <- function(R0, alpha, beta, r, psi, n_moments = 5) {
	stopifnot(n_moments >= 1, n_moments <= 5)

	# rho_k = beta / (beta + k*r)
	rho <- sapply(1:n_moments, function(k) beta / (beta + k * r))

	# Cumulants of the inner sum Y: kappa_k = R0 * rho_k^(psi*alpha) * m_k
	# m_1 = 1 (unconditional mean of W)
	m <- numeric(n_moments)
	m[1] <- 1

	# For n >= 2: m_n = rho_n^((1-psi)*alpha) * D_n / (1 - R0 * rho_n^alpha)
	# where D_n = B_n(kappa_1, ..., kappa_{n-1}, 0)
	# and kappa_k = R0 * rho_k^(psi*alpha) * m_k

	if (n_moments >= 2) {
		k1 <- R0 * rho[1]^(psi * alpha) * m[1]

		# D_2 = k1^2
		D2 <- k1^2
		m[2] <- rho[2]^((1 - psi) * alpha) * D2 / (1 - R0 * rho[2]^alpha)
	}

	if (n_moments >= 3) {
		k2 <- R0 * rho[2]^(psi * alpha) * m[2]

		# D_3 = k1^3 + 3*k1*k2
		D3 <- k1^3 + 3 * k1 * k2
		m[3] <- rho[3]^((1 - psi) * alpha) * D3 / (1 - R0 * rho[3]^alpha)
	}

	if (n_moments >= 4) {
		k3 <- R0 * rho[3]^(psi * alpha) * m[3]

		# D_4 = k1^4 + 6*k1^2*k2 + 4*k1*k3 + 3*k2^2
		D4 <- k1^4 + 6 * k1^2 * k2 + 4 * k1 * k3 + 3 * k2^2
		m[4] <- rho[4]^((1 - psi) * alpha) * D4 / (1 - R0 * rho[4]^alpha)
	}

	if (n_moments >= 5) {
		k4 <- R0 * rho[4]^(psi * alpha) * m[4]

		# D_5 = k1^5 + 10*k1^3*k2 + 10*k1^2*k3 + 15*k1*k2^2 + 5*k1*k4 + 10*k2*k3
		D5 <- k1^5 + 10 * k1^3 * k2 + 10 * k1^2 * k3 +
			15 * k1 * k2^2 + 5 * k1 * k4 + 10 * k2 * k3
		m[5] <- rho[5]^((1 - psi) * alpha) * D5 / (1 - R0 * rho[5]^alpha)
	}

	names(m) <- paste0("m", 1:n_moments)
	m
}

#' Fit 3-parameter generalized gamma to W | survival using 5-moment matching
#'
#' GG(beta_gg, a1, a2) has k-th moment:
#'   M_k = beta_gg^k * Gamma((a1+k)/a2) / Gamma(a1/a2)
#'
#' Fit by minimizing sum of squared standardized moment errors.
#'
#' @param R0    Basic reproduction number
#' @param alpha Shape parameter of Gamma generation interval
#' @param beta  Rate parameter of Gamma generation interval
#' @param r     Malthusian growth rate
#' @param psi   Punctuation parameter
#' @return List with beta_gg, a1, a2, moments, cond_moments, q
fit_W_gengamma <- function(R0, alpha, beta, r, psi) {
	# Unconditional moments
	m <- compute_W_moments(R0, alpha, beta, r, psi, n_moments = 5)

	# Extinction probability and conditional moments
	q <- extinction_prob(R0)
	cond_m <- m / (1 - q)

	# Standardization weights
	eta <- log10(cond_m)

	# GG k-th moment: beta_gg^k * Gamma((a1+k)/a2) / Gamma(a1/a2)
	gg_moments <- function(beta_gg, a1, a2) {
		log_base <- lgamma(a1 / a2)
		sapply(1:5, function(k) {
			beta_gg^k * exp(lgamma((a1 + k) / a2) - log_base)
		})
	}

	# Loss function: sum of squared standardized errors
	loss <- function(par) {
		beta_gg <- par[1]
		a1 <- par[2]
		a2 <- par[3]
		if (beta_gg <= 0 || a1 <= 0 || a2 <= 0) return(1e20)
		M <- tryCatch(gg_moments(beta_gg, a1, a2), error = function(e) rep(NA, 5))
		if (any(is.na(M)) || any(M <= 0)) return(1e20)
		sum(((cond_m - M) / 10^eta)^2)
	}

	# Optimize on log scale for better conditioning
	loss_log <- function(logpar) {
		loss(exp(logpar))
	}

	# Starting values from 2-moment Gamma fit (a2 = 1 recovers ordinary Gamma)
	E_cond <- cond_m[1]
	E2_cond <- cond_m[2]
	var_cond <- E2_cond - E_cond^2
	shape0 <- E_cond^2 / var_cond
	rate0 <- E_cond / var_cond
	beta_gg0 <- 1 / rate0
	a1_0 <- shape0

	# Multi-start: try several a2 values to avoid local minima
	best <- list(value = Inf)
	for (a2_start in c(0.5, 0.75, 1.0, 1.5, 2.0)) {
		fit <- tryCatch(
			optim(
				par = log(c(beta_gg0, a1_0, a2_start)),
				fn = loss_log,
				method = "Nelder-Mead",
				control = list(maxit = 5000)
			),
			error = function(e) list(value = Inf)
		)
		if (fit$value < best$value) best <- fit
	}

	par <- exp(best$par)
	list(
		beta_gg = par[1],
		a1 = par[2],
		a2 = par[3],
		moments = m,
		cond_moments = cond_m,
		q = q,
		convergence = best$convergence,
		loss = best$value
	)
}

# ==============================================================================
# 2. Global parameters
# ==============================================================================

popsize   <- 10000
nsim      <- 1000
threshold <- 100
n_draws   <- 100000
psivals   <- c(0, 0.5, 1)
psi_colors <- c("0" = "red", "0.5" = "blue", "1" = "black")

set.seed(42)

# ==============================================================================
# 3. Loop over pathogens
# ==============================================================================

for (pars in parslist) {

pathogen <- pars$pathogen
T        <- pars$Tgen
alpha    <- pars$alpha
beta     <- pars$beta
R0       <- pars$R0

cat(sprintf("\n===== %s: T=%.2f, alpha=%.2f, R0=%.1f =====\n",
            pathogen, T, alpha, R0))

# --------------------------------------------------------------------------
# 3a. Malthusian growth rate
# --------------------------------------------------------------------------

r_malthusian <- uniroot(
	function(r) R0 * (beta / (beta + r))^alpha - 1,
	interval = c(0, 10))$root

cat(sprintf("  r_malthusian = %.6f\n", r_malthusian))

# --------------------------------------------------------------------------
# 3b. Deterministic time to threshold from renewal equation
# --------------------------------------------------------------------------

ren_out <- renewal_epidemic(R0, alpha, T, popsize)

t_det <- approx(
	x = ren_out$cuminf * popsize,
	y = ren_out$t,
	xout = threshold,
	ties = mean
)$y

cat(sprintf("  Deterministic time to %d cases: %.2f days\n", threshold, t_det))

# --------------------------------------------------------------------------
# 3c. Theoretical W distributions and survival curves for each psi
# --------------------------------------------------------------------------

theory_surv_list_gg <- list()
theory_surv_list_g  <- list()

for (psi in psivals) {
	# Fit generalized gamma via 5-moment matching
	fit_gg <- fit_W_gengamma(R0, alpha, beta, r_malthusian, psi)

	# Also compute 2-moment Gamma
	fit_g <- fit_W_gamma(R0, alpha, beta, r_malthusian, psi)

	cat(sprintf("  psi=%.1f: Gamma(shape=%.3f, rate=%.3f) | GG(beta=%.4f, a1=%.4f, a2=%.4f) loss=%.2e\n",
	            psi, fit_g$shape, fit_g$rate,
	            fit_gg$beta_gg, fit_gg$a1, fit_gg$a2, fit_gg$loss))

	# Sample W | survival from fitted generalized gamma
	# W* = beta_gg * Gamma(a1/a2, 1)^(1/a2)
	W_gg <- fit_gg$beta_gg * rgamma(n_draws, shape = fit_gg$a1 / fit_gg$a2, rate = 1)^(1 / fit_gg$a2)
	t_stoch_gg <- t_det - log(W_gg) / r_malthusian

	# Sample W | survival from fitted 2-moment Gamma
	W_g <- rgamma(n_draws, shape = fit_g$shape, rate = fit_g$rate)
	t_stoch_g <- t_det - log(W_g) / r_malthusian

	theory_surv_list_gg[[as.character(psi)]] <- tibble(
		psi = factor(psi), t_stoch = t_stoch_gg)
	theory_surv_list_g[[as.character(psi)]] <- tibble(
		psi = factor(psi), t_stoch = t_stoch_g)
}

theory_draws_gg_df <- bind_rows(theory_surv_list_gg)
theory_draws_g_df  <- bind_rows(theory_surv_list_g)

# --------------------------------------------------------------------------
# 3d. Load empirical simulation data and build empirical survival curves
# --------------------------------------------------------------------------

cache <- load_cache(pathogen, nsim, popsize, psivals)

if (is.null(cache)) {
	cat(sprintf("  WARNING: v2 cache not found for %s (n=%d, s=%d), skipping\n",
	    pathogen, popsize, nsim))
	next
}

# Extract time to establishment from summary (pre-computed in episims_gamma.R)
# Handle both old cache (time_to_100) and new cache (establishment_time) column names
est_col <- if ("establishment_time" %in% names(cache$summary)) "establishment_time" else "time_to_100"
time_to_threshold <- cache$summary %>%
	filter(established == 1, !is.na(.data[[est_col]])) %>%
	transmute(sim, psi, tinf = .data[[est_col]])

# Build empirical survival curves
t_max <- max(time_to_threshold$tinf)
t_grid <- seq(0, t_max, length.out = 500)

empirical_surv <- time_to_threshold %>%
	group_by(psi) %>%
	summarise(
		t = list(t_grid),
		prop_below = list(sapply(t_grid, function(tt) mean(tinf > tt))),
		.groups = "drop") %>%
	unnest(cols = c(t, prop_below))

# Build theoretical survival curves on the same grid (generalized gamma)
theory_surv_gg <- theory_draws_gg_df %>%
	group_by(psi) %>%
	summarise(
		t = list(t_grid),
		prop_below = list(sapply(t_grid, function(tt) mean(t_stoch > tt))),
		.groups = "drop") %>%
	unnest(cols = c(t, prop_below))

# Build theoretical survival curves on the same grid (2-moment gamma)
theory_surv_g <- theory_draws_g_df %>%
	group_by(psi) %>%
	summarise(
		t = list(t_grid),
		prop_below = list(sapply(t_grid, function(tt) mean(t_stoch > tt))),
		.groups = "drop") %>%
	unnest(cols = c(t, prop_below))

# --------------------------------------------------------------------------
# 3e. Overlay figures
# --------------------------------------------------------------------------

breakvals <- if (t_max > 120) seq(0, 365, by = 15) else seq(0, 365, by = 7)
surv_ylab <- paste0("Proportion not yet reaching ", threshold, " cases")

# Generalized gamma theory overlay
fig_survival_theory_gg <- ggplot() +
	geom_line(data = empirical_surv,
	          aes(x = t, y = prop_below, col = psi),
	          alpha = 0.6, linewidth = 0.8) +
	geom_line(data = theory_surv_gg,
	          aes(x = t, y = prop_below, col = psi),
	          linetype = "dashed", linewidth = 0.8) +
	scale_x_continuous(breaks = breakvals) +
	scale_color_manual(values = psi_colors) +
	labs(x = "Days", y = surv_ylab, col = expression(psi),
	     title = paste0(pathogen, " (gen. gamma theory)")) +
	theme_classic()

save_fig(fig_survival_theory_gg, paste0("fig_survival_100_theory_gg_", pathogen))

# 2-moment gamma theory overlay
fig_survival_theory_g <- ggplot() +
	geom_line(data = empirical_surv,
	          aes(x = t, y = prop_below, col = psi),
	          alpha = 0.6, linewidth = 0.8) +
	geom_line(data = theory_surv_g,
	          aes(x = t, y = prop_below, col = psi),
	          linetype = "dashed", linewidth = 0.8) +
	scale_x_continuous(breaks = breakvals) +
	scale_color_manual(values = psi_colors) +
	labs(x = "Days", y = surv_ylab, col = expression(psi),
	     title = paste0(pathogen, " (gamma theory)")) +
	theme_classic()

save_fig(fig_survival_theory_g, paste0("fig_survival_100_theory_g_", pathogen))

cat(sprintf("  %s: theory overlays saved (GG + Gamma).\n", pathogen))

# --------------------------------------------------------------------------
# 3f. W distribution: empirical histogram with Gamma / Gen. Gamma overlays
# --------------------------------------------------------------------------

# Empirical W | survival: W = exp(r * (t_det - t_emp))
W_empirical <- time_to_threshold %>%
	mutate(W = exp(r_malthusian * (t_det - tinf)))

# Theoretical density functions for each psi
W_density_list <- list()
w_grid <- seq(1e-4, quantile(W_empirical$W, 0.995), length.out = 500)

for (psi in psivals) {
	fit_g  <- fit_W_gamma(R0, alpha, beta, r_malthusian, psi)
	fit_gg <- fit_W_gengamma(R0, alpha, beta, r_malthusian, psi)

	# Gamma density
	d_g <- dgamma(w_grid, shape = fit_g$shape, rate = fit_g$rate)

	# Generalized gamma density:
	# f(w) = (a2 / beta_gg) * (w/beta_gg)^(a1-1) * exp(-(w/beta_gg)^a2) / Gamma(a1/a2)
	b <- fit_gg$beta_gg; a1 <- fit_gg$a1; a2 <- fit_gg$a2
	log_d_gg <- log(a2) - log(b) + (a1 - 1) * log(w_grid / b) -
		(w_grid / b)^a2 - lgamma(a1 / a2)
	d_gg <- exp(log_d_gg)

	W_density_list[[as.character(psi)]] <- tibble(
		psi = factor(psi), w = w_grid,
		Gamma = d_g, `Gen. Gamma` = d_gg) %>%
		pivot_longer(cols = c(Gamma, `Gen. Gamma`),
		             names_to = "fit", values_to = "density")
}

W_density_df <- bind_rows(W_density_list)

fig_W_hist <- ggplot(W_empirical, aes(x = W)) +
	geom_histogram(aes(y = after_stat(density)), bins = 60,
	               fill = "white", col = "darkgrey") +
	geom_line(data = W_density_df,
	          aes(x = w, y = density, col = fit, linetype = fit),
	          linewidth = 0.8) +
	scale_color_manual(values = c("Gamma" = "blue", "Gen. Gamma" = "red")) +
	scale_linetype_manual(values = c("Gamma" = "dashed", "Gen. Gamma" = "solid")) +
	facet_wrap(~psi, nrow = 1, scales = "free_y",
	           labeller = label_bquote(psi == .(as.numeric(as.character(psi))))) +
	labs(x = "W | survival", y = "Density",
	     col = "Fit", linetype = "Fit",
	     title = pathogen) +
	theme_classic() +
	theme(legend.position = "bottom")

save_fig(fig_W_hist, paste0("fig_W_hist_", pathogen))

cat(sprintf("  %s: W histogram saved.\n", pathogen))

} # end pathogen loop
